// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQBolrpmbiqUIDs3W131HkNSjl1z3Kn8k',
    appId: '1:1072194399425:web:745527ad0df3e8f261f840',
    messagingSenderId: '1072194399425',
    projectId: 'expensesapp-59b6e',
    authDomain: 'expensesapp-59b6e.firebaseapp.com',
    storageBucket: 'expensesapp-59b6e.appspot.com',
    measurementId: 'G-PEQPL172F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjfeyylLZqEaumKzMvap8PTAimoAq-_mQ',
    appId: '1:1072194399425:android:31fdab4d0f0b791d61f840',
    messagingSenderId: '1072194399425',
    projectId: 'expensesapp-59b6e',
    storageBucket: 'expensesapp-59b6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfdNFBs_lHP4FtSKjr019bL2KttdwZN18',
    appId: '1:1072194399425:ios:81cdc11816caf0db61f840',
    messagingSenderId: '1072194399425',
    projectId: 'expensesapp-59b6e',
    storageBucket: 'expensesapp-59b6e.appspot.com',
    iosClientId: '1072194399425-fa1vs74vptslhjkm5gr12i3p4euks86s.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfdNFBs_lHP4FtSKjr019bL2KttdwZN18',
    appId: '1:1072194399425:ios:81cdc11816caf0db61f840',
    messagingSenderId: '1072194399425',
    projectId: 'expensesapp-59b6e',
    storageBucket: 'expensesapp-59b6e.appspot.com',
    iosClientId: '1072194399425-fa1vs74vptslhjkm5gr12i3p4euks86s.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapp',
  );
}
